### ISSUE TITLE
Capture the result of the email sent and show it as s column

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#113]
Requested at https://wordpress.org/support/topic/suggestion-add-a-status-or-error-column/

---

## Attached PR(s)
https://github.com/sudar/email-log/pull/163

**Comment by mariadanieldeepak** [comment]
@sudar,

The route I took seems to get challenging.

I tried to capture the result of the email using the following hook `wp_mail_failed`

https://github.com/WordPress/WordPress/blob/master/wp-includes/pluggable.php#L502

The reason it seems to get challenging is because,

- SMTP plugins like [WP Mail SMTP](https://wordpress.org/plugins/wp-mail-smtp/) doesn't trigger these hooks when sending emails fail.
- When this hook is triggered we may **NOT** know which email in the DB failed. I say this because, assume a scenario where the same email is sent multiple times and only one or few emails out of those failed. In that case, how do we know which ones failed and which ones were sent successfully.

If I didn't make myself clear, can we get in to a call to discuss?

**Comment by mariadanieldeepak** [comment]
Send Grid
Invalid email

**Comment by sudar** [comment]
@mariadanieldeepak 

Do you still have any questions for me on this?

**Comment by mariadanieldeepak** [comment]
@sudar,

I've made progress on this one at https://github.com/sudar/email-log/tree/124-feature/notify-admins-on-email-threshold-email-failure

Blocked:

- Unable to retrieve the log item by the log item data. This is mainly because when I provide data to test, the expected results are not showing up. May be my data setup could be wrong. I find this going wrong because of the `headers` column where the value contains `\n`

**Comment by mariadanieldeepak** [comment]
@sudar,

The development is completed.

I couldn't arrive to email failure scenario by the methods we discussed. However, I manually threw an exception that made the hook to trigger. And the hooked callback updated the DB record as expected.

![image](https://user-images.githubusercontent.com/17510033/45824765-5c44ba80-bd0e-11e8-8d03-501fd147595a.png)
