### ISSUE TITLE
Show email content in escaped form

### ISSUE THREAD

**Issue by johnbillion** [sudar/email-log#114]
When a new user is added to a site, the email which gets sent out to the user contains a link which is contained within `<` and `>` brackets. Ref: https://core.trac.wordpress.org/browser/tags/4.8.2/src/wp-includes/pluggable.php?marks=1823#L1820

When viewing this email in the Email Log, this link is not visible because the browser thinks it's an HTML tag. The entire contents of the email body should be passed through `esc_html()` before being displayed.

**Comment by sudar** [comment]
@johnbillion 

Thanks for reporting the issue and also for the tip to fix it.

I will fix it and make a release.

**Comment by sudar** [comment]
@johnbillion 

On exploring this further I found that this is happening only in the preview tab of the email content where we provide an option for the users to preview how their html emails look like.

I think the confusion is mostly because the preview option was the default one.

I have now made the Raw content tab as the default one and also modified the tab names to be more descriptive.
