### ISSUE TITLE
Potential incompatibility with wp-ses plugin

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#194]
Reported at https://wordpress.org/support/topic/bug-attachments-dropped/#post-10976514

> I was trying to use this plugin, v2.2.5, but when Email Log was enabled, emails would send without their attachments. Once I disabled it, attachments worked again.

> I was also using WP SES 0.8.1 (https://wordpress.org/plugins/wp-ses/) although I didn’t test the problem with that disabled (I don’t have any other SMTP service).

---

## Attached PR(s)
https://github.com/sudar/email-log/pull/195

**Comment by mariadanieldeepak** [comment]
@sudar,

I tried signup for an AWS account to access Amazon SES. However, it looks like I'll have to wait for 24 hours before my account gets activate.

![image](https://user-images.githubusercontent.com/17510033/49848368-d7dc7200-fdfa-11e8-9946-ab43d9af8390.png)

Could you try signing up for an AWS account? The AWS account is required in order to use WP SES plugin.

![image](https://user-images.githubusercontent.com/17510033/49848424-04908980-fdfb-11e8-81b2-7fa1a1ff1260.png)

**Comment by mariadanieldeepak** [comment]
@sudar,

I'm able to replicate the reported issue and I'm working on the fix.

**Comment by mariadanieldeepak** [comment]
@sudar,

I've figured out what the issue is.

You can see that the following line doesn't send the `attachment` arg as opposed to the [WordPress filter](https://developer.wordpress.org/reference/hooks/wp_mail/) and that is the root cause.

https://github.com/wp-plugins/wp-ses/blob/master/wp-ses.php#L493

**Comment by sudar** [comment]
@mariadanieldeepak 

Re-assigning this to you since there are some pending review comments.
