### ISSUE TITLE
Change the color of the email log row if email failed to be sent

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#215]

**Comment by mariadanieldeepak** [comment]
@sudar,

May I suggest something here?

I would prefer to have an Icon rather than changing the entire row's color. It occurs that an icon would be more pleasing than the row color. Let me know your thoughts.

![image](https://user-images.githubusercontent.com/17510033/56706271-f56b0200-6731-11e9-8b82-f5db096a6901.png)

![image](https://user-images.githubusercontent.com/17510033/56706275-fac84c80-6731-11e9-86f9-82e00007662f.png)

The Icon that I used is from here https://www.flaticon.com/free-icon/tick-inside-circle_61222#term=tick&page=1&position=9 The author should be credited in the README or similar file.

**Comment by sudar** [comment]
@mariadanieldeepak 

I am fine to use the icon, but let's show the icon for both success and failure cases.

**Comment by mariadanieldeepak** [comment]
@sudar,

> I am fine to use the icon, but let's show the icon for both success and failure cases.

Done.

![image](https://user-images.githubusercontent.com/17510033/61167167-0caed400-a558-11e9-8e07-875ee69cc612.png)

![image](https://user-images.githubusercontent.com/17510033/61167169-11738800-a558-11e9-832e-038430f94272.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

Looks good. Is this ready for review?

**Comment by sudar** [comment]
@mariadanieldeepak 

Looks like Style CI tests are failing. Fix them and re-assign them for review.
