### ISSUE TITLE
System Info section

### ISSUE THREAD

**Issue by sudar** [sudar/email-log#97]
- [x] Create a new menu called 'System Info'
- [x] When a user clicks it he should see a new 'System Info' page
- [x] It should have a textbox like Bulk Delete that shows the different information about the current WordPress install
- [x] There should be a button called 'Download', clicking which should download the system info in a text file.

Refer to Bulk Delete. It has all the functionalities. You just have to take the code from there and adapt it for Email Log.

**Comment by sudar** [comment]
@mariadanieldeepak 

Anand worked on it long time ago and created a PR at #145 

Find out the status of this and implement any missing features.

**Comment by mariadanieldeepak** [comment]
@sudar,

The System Info only shows `editor` in Allowed Roles.

![image](https://user-images.githubusercontent.com/17510033/48518188-cc933680-e88e-11e8-9488-73775c26e8e0.png)

Where as in actuality, it should also show `administrator`.

![image](https://user-images.githubusercontent.com/17510033/48518181-c8671900-e88e-11e8-822b-f5cc9b75b2d3.png)

Kindly let me know if this is intentional.

**Comment by sudar** [comment]
@mariadanieldeepak 

I have modified the label to make it more consistent.
